apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon-set-node-selector
  labels:
    app: daemon-set-node-selector
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - daemon-set-nginx-node-selector
  template:
    metadata:
      name: daemon-template-nginx-node-selector
      labels:
        app: daemon-set-nginx-node-selector
    spec:
      nodeSelector:
        gpu: 'true'
      containers:
      - name: daemon-set-app-nginx-node-selector
        image: nginx:stable-alpine3.17-slim
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 1
