apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hpa
  labels:
    app: node-hpa
spec:
  replicas: 2 # recomended to use minReplica HPA
  selector:
    matchLabels:
      app: node-hpa
  template:
    metadata:
      labels:
        app: node-hpa
    spec:
      containers:
      - name: node-hpa
        image: khannedy/nodejs-web:3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: node-hpa-service
spec:
  type: NodePort
  selector:
    app: node-hpa
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30010

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-hpa # refer to deployment use
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70


