apiVersion: v1
kind: Pod
metadata:
  name: nginx-accessor-service
  labels:
    name: nginx-accessor-service
spec:
  containers:
  - name: nginx-accessor-service
    image: khannedy/nginx-curl
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
