apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-port-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-port-service
  template:
    metadata:
      name: node-port-service
      labels:
        app: node-port-service
    spec:
      containers:
      - name: nginx-node-port-service
        image: nginx:stable-alpine3.17-slim
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: node-port-service
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
