apiVersion: v1
kind: Pod
metadata:
  name: nginx-probe
  labels:
    name: nginx-probe
spec:
  containers:
  - name: nginx-probe2
    image: nginx:stable-alpine3.17-slim
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    # check everytime like healthcheck docker
    livenessProbe:
      # just 1 handler, exec, tcp or http
      # exec:
      #   command:
      #   # - /tmp/healthy
      #   - cat
      # tcpSocket:
      #   port: 80
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    # check if ready to receive traffic
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
    startupProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 0
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
