apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-sharing-volume
  labels:
    app: rs-sharing-volume
spec:
  replicas: 2
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - rs-sharing-volume
  template:
    metadata:
      name: rs-sharing-volume
      labels:
        app: rs-sharing-volume
    spec:
      containers:
      - name: rs-sharing-volume
        image: khannedy/nodejs-writer
        volumeMounts:
        - mountPath: /app/html
          name: html
      - name: nginx
        image: nginx:stable-alpine3.17-slim
        volumeMounts:
        - mountPath: /usr/share/nginx/html # this is pov by nginx container will be create next
          name: html # by this. k8s will register volume to this container. and why mount path use /usr/share/nginx due it is default by image nginx.
        ports:
        - containerPort: 80
      volumes:
      - name: html
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: rs-sharing-volume-service
spec:
  type: NodePort
  selector:
    app: rs-sharing-volume
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30003


