apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod-curl
  labels:
    app: try-multi-container-pod
    env: local
spec:
  containers:
  - name: multi-container-pod-curl
    image: khannedy/nginx-curl
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 81
