apiVersion: v1
kind: PersistentVolume
metadata:
  name: nodejs-pv-volume
spec:
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/location
  accessModes:
  - ReadWriteMany
  # persistentVolumeReclaimPolicy: Recycle
# storageClassName: slow
# mountOptions:
# - hard
# - nfsvers=4.1
# nfs:
#   path: /tmp
#   server: 172.17.0.2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nodejs-pv-claim # pvc prefix must be same with pv. ends with -claim
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany

---
apiVersion: apps/v1 # apps
kind: ReplicaSet
metadata:
  name: nodejs-pv
  labels:
    app: nodejs-pv
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nodejs-pv
  template:
    metadata:
      name: nodejs-pv-template
      labels:
        app: nodejs-pv
    spec:
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: nodejs-pv-claim
      containers:
      - name: nodejs-pv
        image: khannedy/nodejs-writer
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /app/html
          name: html


