apiVersion: v1
kind: ConfigMap
metadata:
  name: node-config-map
data:
  APPLICATION: This is config map
  VERSION: 1.0.0
  namaku: caco

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-config-map
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-config-map
  template:
    metadata:
      name: node-config-map-pod
      labels:
        app: node-config-map
    spec:
      containers:
      - name: node-config-map-pod
        image: khannedy/nodejs-env
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: node-config-map

---
apiVersion: v1
kind: Service
metadata:
  name: node-config-map
spec:
  type: NodePort
  selector:
    app: node-config-map
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30004

