apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-ingress
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-ingress
  template:
    metadata:
      name: node-ingress
      labels:
        app: node-ingress
    spec:
      containers:
      - name: nginx-node-ingress
        image: nginx:stable-alpine3.17-slim
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: node-ingress
spec:
  selector:
    app: node-ingress
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
# apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: node-ingress
  labels:
    name: node-ingress
spec:
  rules:
  - host: nginx.ingress.localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: node-ingress
            port:
              number: 80

