apiVersion: v1
kind: ConfigMap
metadata:
  name: node-downward-api
  labels:
    app: node-downward-api
data:
  APPLICATION: This is config map
  VERSION: 1.0.0
  namaku: caco

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-downward-api
  labels:
    app: node-downward-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-downward-api
  template:
    metadata:
      name: node-downward-api-pod
      labels:
        app: node-downward-api
    spec:
      containers:
      - name: node-downward-api-pod
        image: khannedy/nodejs-env
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: node-downward-api
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name # https://kubernetes.io/docs/concepts/workloads/pods/downward-api/
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: RES_CPU
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu

---
apiVersion: v1
kind: Service
metadata:
  name: node-downward-api
  labels:
    app: node-downward-api
spec:
  type: NodePort
  selector:
    app: node-downward-api
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30006

